version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Madrid"
    target-branch: "develop"
    versioning-strategy: "increase"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automated"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      major-updates:
        applies-to: version-updates
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/Madrid"
    target-branch: "develop"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "automated"
