import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Providers } from './providers';
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const PrivacySetings = () => {
  return (
    <>
    <Script
      id="humanity-options"
      strategy="afterInteractive"
      dangerouslySetInnerHTML={{
        __html: `
          var huOptions = {
            'appID': 'perebarcelopsicologocom-5e860ea',
            'currentLanguage': 'en',
            'blocking': true,
            'globalCookie': false
          }
        `
      }}
    />
    <Script
      id="humanity-banner"
      src="https://cdn.hu-manity.co/hu-banner.min.js"
      strategy="afterInteractive"
    />
  </>
    // <Script
    //   id="humanity"
    //   src="https://cdn.hu-manity.co/hu-banner.min.js"
    //   strategy="beforeInteractive"
    // >
    //   {`
    //         var huOptions = {
    //             'appID': 'perebarcelopsicologocom-5e860ea',
    //             'currentLanguage': 'en',
    //             'blocking': true,
    //             'globalCookie': false
    //             }
    //             `}
    // </Script>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <head>
        <PrivacySetings />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
